config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :albums, only: [:index, :show]

  resources :reviews, only: [:index, :new, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :new]
  end
  resources :tags do
    collection do 
      get :search
    end
  end
  root "albums#index"
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :reviews

  def self.find_album(title, artist_id)
    album = Album.find_by(title: title, artist_id: artist_id)
    unless album.present?
      album = Album.create!(title: title, artist_id: artist_id)
    end
    album
  end

  def another_albums()
    artist = self.artist
    artist.albums.where.not(id: self.id).select { |album| album.reviews.count > 0 }
  end

  with_options presence: true do
    validates :title
    validates :artist_id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy

  def self.find_artist(name)
    artist = Artist.find_by(name: name)
    unless artist.present?
      artist = Artist.create!(name: name)
    end
    artist
  end

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :content, presence: true

  delegate :strip_tags, to: 'ApplicationController.helpers'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :reviews_tags, dependent: :destroy
  has_many :tags, through: :reviews_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :album

  # 当該レビューに対して、引数に渡したユーザーがいいねを押しているかの判断
  def liked_by(user_id)
    likes.where(user_id: user_id).exists?
  end

  validates :content, presence: true
end

app/models/reviews_tag.rb
class ReviewsTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :reviews_tags
  has_many :reviews, through: :reviews_tags

  def self.find_tag(names)
    tags = []
    names.each do |name|
      tag = Tag.find_or_create_by!(name: name)
      tags << tag
    end
    tags
  end

  def self.search(name)
    Tag.where('name LIKE(?)', "%#{name}%")
  end

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  include SpotifyMethod
  def index
    @albums = Album.all.order(id: 'DESC').includes(:artist, :reviews).select { |album| album.reviews.count > 0 }
  end

  def show
    @review_form = ReviewForm.new
    @album = Album.includes(:artist, reviews: [:tags, :likes]).find(params[:id])
    @tracks = @album.spotify_id ? get_tracks(@album.spotify_id) : nil
    @comment = Comment.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth, if: :production?

  def configure_permitted_parameters
    devise_keys = [:nickname]
    devise_parameter_sanitizer.permit(:sign_up, keys: devise_keys)
  end

  private
  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.basic_auth[:user_name] && password == Rails.application.credentials.basic_auth[:password]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_review, only: [:create]

  def create
    if user_signed_in?
      @comment = @review.comments.new(comment_params)
      if @comment.save
        respond_to do |format|
          format.json
          format.html { redirect_to review_path(@review) }
        end
      else
        flash[:alert] = '文字を入力してください'
      end
    else
      flash[:alert] = 'ログインが必要です'
      redirect_to new_user_session_path
    end
  end

  def new

  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, review_id: @review.id)
  end

  def set_review
    @review = Review.find(params[:review_id])
  end
end

app/controllers/concerns/spotify_method.rb
module SpotifyMethod
  extend ActiveSupport::Concern
  
  # artistのspotify情報取得する
  def get_artist_spotify(artist_name)
    artist_name.present? ? RSpotify::Artist.search(artist_name).first : nil
  end

  # 引数に渡したalbumのspotify情報を取得する
  def get_album_spotify(artist_spotify_id, album_name)
    artist = RSpotify::Artist.find(artist_spotify_id)
    album = artist.albums(album_type: 'single', limit: 50).find { |album| album.name.include?(album_name) }
    unless album
      album = artist.albums(album_type: 'album', limit: 50).find { |album| album.name.include?(album_name) }
      unless album
        album = artist.albums(album_type: 'compilation', limit: 50).find { |album| album.name.include?(album_name) }
        unless album
          album_name = "*#{album_name.gsub(/\s/, '%20')}*"
          album = RSpotify::Album.search(album_name).map { |search_album| 
                    search_album.artists.find { |search_artist| 
                      search_artist.id == artist_spotify_id }
                    }[0]
        end
      end
    end
    album ? album : nil
  end

  # アルバムの画像を探す
  def get_album_image(album_spotify_id)
    image = RSpotify::Album.find(album_spotify_id)
    image.images[0]['url']
  end

  # トラックの取得
  def get_tracks(album_spotify_id)
    RSpotify::Album.find(album_spotify_id).tracks
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_review, only: [:create, :destroy]

  def create
    if user_signed_in?
      like = Like.new(flag: 1, user_id: current_user.id, review_id: @review.id)
      like.save

      # ハートのアニメーションを動かすため
      sleep(0.45)
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, review_id: @review.id)
    like.delete
  end


  private

  def set_review
    @review = Review.find(params[:review_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include SpotifyMethod
  def index

  end

  def new
    @review_form = ReviewForm.new
    unless user_signed_in?
      flash[:alert] = 'ログインが必要です'
      redirect_to new_user_session_path
    end
  end

  def create
    @review_form = ReviewForm.new(review_params)
    path = Rails.application.routes.recognize_path(request.referer)
    if @review_form.save
      if path[:controller] == 'albums'
        flash[:notice] = 'レビューを投稿しました'
        redirect_to album_path(path[:id])
      else
        flash[:notice] = 'レビューを投稿しました'
        redirect_to root_path
      end
    else
      render :new
    end
  end

  def show
    @review = Review.includes(:album).find(params[:id])
    @comment = Comment.new
    @tracks = @review.album.spotify_id ? get_tracks(@review.album.spotify_id) : nil
  end

  def destroy
    review = Review.find(params[:id])
    if review.destroy
      if review.album.reviews.count == 0
        flash[:warning] = 'レビューを削除しました'
        redirect_to root_path
      else
        flash[:warning] = 'レビューを削除しました'
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:warning] = 'レビューを削除できませんでした'
    end
  end

  private
  def review_params
    params.require(:review_form).permit(:artist_name, :album_name, :review_content, tags: []).merge(user_id: current_user.id)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def search
    @tags = Tag.search(params[:tag])
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/albums/_album_info.html.haml
.album-show__detail
  .album-show__detail__album-image
    = image_tag album.image, class: 'album-show__detail__album-image__image'
  .album-show__detail__info
    .album-show__detail__info__album-title
      = album.title
    .album-show__detail__info__artist-name
      = album.artist.name
  .tracks
    - if tracks
      .tracks__header
        .tracks__header__track
          Tracks
        .tracks__header__sample
          Sample
      - tracks.each do |track|
        .track
          .track__info
            .track__info__number
              = "#{track.track_number}."
            .track__info__name
              = track.name
          - if track.preview_url
            .track__audio
              = button_tag type: 'button', class: 'track__audio__button' do
                = fa_icon 'play-circle'
              = button_tag type: 'button', class: 'track__audio__button--stop' do
                = fa_icon 'pause-circle'
              %audio{src: "#{track.preview_url}", class: "prev-audio"}

app/views/albums/_another-albums.html.haml
.another-albums
  .another-albums__header
    = album.artist.name
    %span
      の他のアルバム
  .another-albums__container
    - if album.another_albums().present?
      - album.another_albums().each do |another_album|
        .another-albums__container__album
          = link_to album_path(another_album) do
            .album-image
            - if another_album.image.present?
              = image_tag another_album.image, class: 'album-image__content'
            - else
              = image_tag 'no_image.png', class: 'album-image__content'
            .album-info
              .album-info__album-title.over-scroll
                = another_album.title

app/views/albums/index.html.haml
= render partial: 'layouts/header'

.wrapper
  .recomu-top
    .albums
      - @albums.each do |album|
        .album{ontouchstart: ''}
          = link_to album_path(album) do
            .album__album-image
              = image_tag album.image, class: 'album__album-image__image'
            .album__info
              .album__info__album-title
                %span.over-scroll
                  = album.title
              .album__info__artist-name
                %span.over-scroll
                  = album.artist.name

= render partial: 'layouts/post'

app/views/albums/show.html.haml
= render partial: 'layouts/header'

.wrapper
  .album-show
    .upper
      = render partial: 'album_info', locals: {album: @album, tracks: @tracks}
      
      .border-radius.pjax-wrapper
        #pjax-container
          .reviews
            .reviews__header
              Reviews
            - @album.reviews.reverse.each do |review|
              .review
                .review__user-name
                  = review.user.nickname
                %ul.review__tags
                  - review.tags.each do |tag|
                    %li.review__tags__tag
                      = tag.name
                = link_to review_path(review), class: 'review__link js-pjax' do
                  .review__content
                    .review__content__text
                      = simple_format(review.content)

                %ul.review__bottom
                  .review__bottom--left
                    - if user_signed_in?
                      - if review.user.id == current_user.id
                        %li.review-delete.js-modal-delete-review{data: {target: "modal--delete-review__#{review.id}"}}
                          = fa_icon 'trash', class: 'review-delete__icon'

                  .review__bottom--right
                    %li.comment-icon.js-modal-open{data: {target: "modal--#{review.id}"}}
                      = fa_icon 'comment-o', class: 'comment-icon__icon'
                      %span.comment-icon__count
                        = review.comments.count
                    %li.like{id: "like--#{review.id}"}
                      = render partial: 'likes/like', locals: {review: review}
                  
                = render partial: 'modals/comment', locals: {review: review}
                = render partial: 'modals/review-delete', locals: {review: review}


          .post
            - if user_signed_in?
              = button_tag '', class: "post__button", id: 'js-modal-review' do
                = fa_icon "edit", class: 'post__button__edit'
                %p.post__button__message
                  Post
            - else
              = link_to new_user_session_path, class: 'post__button' do
                = fa_icon "edit", class: 'post__button__edit'
                %p.post__button__message
                  Post

    .bottom  
      = render partial: 'another-albums', locals: {album: @album}
  
  = render partial: 'modals/review', locals: {album: @album}

app/views/comments/_modal.html.haml
.modal.js-modal{id: "modal--#{review.id}"}
  .modal__bg.js-modal-close
  .modal__content

    .modal__content__close
      = link_to '', class: 'js-modal-close' do
        = fa_icon 'close', class: 'modal__content__close__icon'
    
    .modal__content__review
      .modal__content__review__info
        .modal__content__review__info__user-name
          = review.user.nickname
        .modal__content__review__info__tags
          - review.tags.each do |tag|
            .modal__content__review__info__tags__tag
              = tag.name
      .modal__content__review__content
        = simple_format(review.content)
    
    .post-comment
      = form_with model: [review, @comment], local: true do |f|
        = f.text_area :content, class: 'post-comment__text'
        .post-comment__submit
          = f.submit 'Comment', class: 'post-comment__submit__button', data: {'disabled-with': '投稿中…'}

app/views/form/_review_form.html.haml
.create-review
  .create-review__header
    Post Review
  = form_with model: review_form, url: reviews_path, class: "review-form", local: true do |f|
    .review-form__artist
      = f.label :artist_name, "Artist", class: "review-form__label"
      - if controller.action_name == 'show'
        = f.text_field :artist_name, class: "review-form__text-field", value: album.artist.name
      - else
        = render partial: 'layouts/error-message', locals: {model: review_form, column: 'artist_name'}
        = f.text_field :artist_name, class: "review-form__text-field"
    .review-form__album
      = f.label :album_name, "Album / Single", class: "review-form__label"
      - if controller.action_name == 'show'
        = f.text_field :album_name, class: "review-form__text-field", value: album.title
      - else
        = render partial: 'layouts/error-message', locals: {model: review_form, column: 'album_name'}
        = f.text_field :album_name, class: "review-form__text-field"
    .review-form__tag
      = f.label :name, "Tags", class: "review-form__label", for: 'tag-field', name: "review_form[tags][]"
      .review-form__tag__container
        = f.text_field :name, class: "review-form__text-field--tag", id: 'tag-field', name: "review_form[tags][]"
        .tags-incremental

    .review-form__tag__add-button
      = button_tag 'Add Tag', type: 'button', class: 'tag-button--add', id: 'tag-add-button'

    .review-form__review
      = f.label :review_content, "Review",class: "review-form__label"
      = render partial: 'layouts/error-message', locals: {model: review_form, column: 'review_content'}
      = f.text_area :review_content, class: "review-form__text-area"

    = f.submit "Post", class: "review-form__submit"

app/views/layouts/_error-message.html.haml
- if model.errors.full_messages_for(column.to_sym).present?
  .error-messages
    %span
      *
    = model.errors.full_messages_for(column.to_sym)[0]

app/views/layouts/_flash_messages.html.haml
- if flash.present?
  .flash-wrapper
    - flash.each do | message_type, message |
      %div{class: "alert alert--#{message_type}"}
        = message

app/views/layouts/_header.html.haml
%header
  .title-logo
    = link_to root_path do
      = image_tag "recomu_logo.png", {class: "title-logo__image"}
  .buttons
    = link_to root_path, class: "button", title: '検索' do
      = fa_icon "search"
    - if user_signed_in?
      = link_to new_user_session_path, class: "button" do
        = fa_icon "cogs"
      = link_to destroy_user_session_path, class: "button", method: "delete", title: 'ログアウト' do
        = fa_icon "sign-out"
    - else
      = link_to new_user_session_path, class: "button", alt: 'ログイン' do
        = fa_icon "sign-in"

app/views/layouts/_post.html.haml
.post
  = link_to new_review_path, class: "post__button" do
    = fa_icon "edit", class: 'post__button__edit'
    %p.post__button__message
      Post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Recomu
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: '//cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.6/jquery.pjax.js'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
  %body{ontouchstart: ''}
    = render partial: 'layouts/flash_messages'
    = yield

app/views/likes/_like.html.haml
- if user_signed_in? && review.liked_by(current_user.id)
  = link_to review_like_path(review_id: review.id, id: review.likes[0].id), method: :delete, class: 'like__button', remote: true do
    = fa_icon 'heart', class: 'like__icon--liked'
  %span.like__count
    = review.likes.where(flag: 1).count

- else
  = link_to review_likes_path(review), method: :post, class: 'like__button', remote: true do
    = fa_icon 'heart-o', class: 'like__icon'
  %span.like__count
    = review.likes.where(flag: 1).count

app/views/likes/create.js.haml
$("#like--#{@review.id}").html("#{j(render partial: 'like', locals: {review: @review})}")

app/views/likes/destroy.js.haml
$("#like--#{@review.id}").html("#{j(render partial: 'like', locals: {review: @review})}")

app/views/modals/_comment.html.haml
.modal.js-modal{id: "modal--#{review.id}"}
  .modal__bg.js-modal-close
  .modal__content

    .modal__content__close
      = link_to '', class: 'js-modal-close' do
        = fa_icon 'close', class: 'modal__content__close__icon'
    
    .modal__content__review
      .modal__content__review__info
        .modal__content__review__info__user-name
          = review.user.nickname
        .modal__content__review__info__tags
          - review.tags.each do |tag|
            .modal__content__review__info__tags__tag
              = tag.name
      .modal__content__review__content
        = simple_format(review.content)
    
    .post-comment
      = form_with model: [review, @comment], local: true do |f|
        = f.text_area :content, class: 'post-comment__text'
        .post-comment__submit
          = f.submit 'Comment', class: 'post-comment__submit__button', data: {'disabled-with': '投稿中…'}

app/views/modals/_review-delete.html.haml
.delete-review.modal.js-modal{id: "modal--delete-review__#{review.id}"}
  .modal__bg.js-modal-close

  .modal__content
    .delete-review__window
      .delete-review__window__header
        レビューを削除しますか？
      .delete-review__window__text
        この操作は取り消せません。本当に削除しますか？
      .delete-review__window__button
        .delete-review__window__button--cancel
          = link_to '', class: 'delete-review__window__button--cancel__link js-modal-close' do
            キャンセル
        .delete-review__window__button--delete
          = link_to review_path(review), class: 'delete-review__window__button--delete__link', method: :delete do
            削除

app/views/modals/_review.html.haml
.create-review.modal.js-modal#post-review
  .modal__bg.js-modal-close

  .modal__content
    .modal__content__close
      = link_to '', class: 'js-modal-close' do
        = fa_icon 'close', class: 'modal__content__close__icon'
    = render partial: 'form/review_form', locals: { review_form: @review_form, album: @album }

app/views/reviews/new.html.haml
:javascript
  window.onload = addToNewUrl();

= render partial: 'layouts/header'


.wrapper
  = render partial: 'form/review_form', locals: { review_form: @review_form }

app/views/reviews/show.html.haml
= render partial: 'layouts/header'

.wrapper
  .album-show
    .upper
      = render partial: 'albums/album_info', locals: {album: @review.album, tracks: @tracks}

      .border-radius.pjax-wrapper
        #pjax-container
          .review
            .review__header
              Review
            .review__info
              .review__info__user-name
                = @review.user.nickname
              .review__info__tags
                - @review.tags.each do |tag|
                  .review__info__tags__tag
                    = tag.name
            .review__content
              = simple_format(@review.content)
            
            %ul.review__bottom
              %li.comment-icon
                = fa_icon 'comment-o', class: 'comment-icon__icon'
                %span.comment-icon__count
                  = @review.comments.count
            
              %li.like{id: "like--#{@review.id}"}
                = render partial: 'likes/like', locals: {review: @review}
          
          %ul.comments#comments
            - @review.comments.reverse_each do |comment|
              %li.comment
                .comment__user-name
                  = comment.user.nickname
                .comment__time
                  = l comment.created_at, format: :short
                .comment__content
                  = simple_format(h(comment.content))

          .post-comment
            = form_with model: [@review, @comment], id: 'comment-form' do |f|
              = f.text_area :content, class: 'post-comment__text'
              .post-comment__submit
                = f.submit 'Comment', class: 'post-comment__submit__button',id: 'post-comment__submit', data: {'disabled-with': '投稿中…'}
    .bottom
      = render partial: 'albums/another-albums', locals: {album: @review.album}

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to ">> Log in", new_session_path(resource_name), class: 'devise-link'
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to ">> Sign up", new_registration_path(resource_name), class: 'devise-link'
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/